"""add relation for work table

Revision ID: 48778bb90ea6
Revises: a661f2244528
Create Date: 2024-08-25 23:28:04.463676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48778bb90ea6"
down_revision: Union[str, None] = "a661f2244528"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pet_work_times", sa.Column("work_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_pet_work_times_work_id_works"),
        "pet_work_times",
        "works",
        ["work_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_pet_work_times_work_id_works"),
        "pet_work_times",
        type_="foreignkey",
    )
    op.drop_column("pet_work_times", "work_id")
    # ### end Alembic commands ###
