"""add pet feed time table

Revision ID: ed8b38f15488
Revises: 33fa94f3ecf9
Create Date: 2024-08-19 20:45:19.374407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed8b38f15488"
down_revision: Union[str, None] = "33fa94f3ecf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pet_feed_times",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("feed_time", sa.DateTime(), nullable=False),
        sa.Column("next_feed_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["pets.telegram_id"],
            name=op.f("fk_pet_feed_times_telegram_id_pets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pet_feed_times")),
        sa.UniqueConstraint(
            "telegram_id", name=op.f("uq_pet_feed_times_telegram_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet_feed_times")
    # ### end Alembic commands ###
