"""create pet work time table

Revision ID: 52c8626f1b15
Revises: ed8b38f15488
Create Date: 2024-08-20 01:03:57.776906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52c8626f1b15"
down_revision: Union[str, None] = "ed8b38f15488"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pet_work_times",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("work_time", sa.DateTime(), nullable=False),
        sa.Column("next_work_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["pets.telegram_id"],
            name=op.f("fk_pet_work_times_telegram_id_pets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pet_work_times")),
        sa.UniqueConstraint(
            "telegram_id", name=op.f("uq_pet_work_times_telegram_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet_work_times")
    # ### end Alembic commands ###
