"""create work table

Revision ID: a661f2244528
Revises: 82b6aa1b1953
Create Date: 2024-08-24 00:02:57.414800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a661f2244528"
down_revision: Union[str, None] = "82b6aa1b1953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_types",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_types")),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_reward", sa.Integer(), nullable=False),
        sa.Column("max_reward", sa.Integer(), nullable=False),
        sa.Column("chance_no_reward", sa.Integer(), nullable=False),
        sa.Column("chance_injury", sa.Integer(), nullable=False),
        sa.Column("work_type_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_type_id"],
            ["work_types.id"],
            name=op.f("fk_works_work_type_id_work_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_works")),
        sa.UniqueConstraint("name", name=op.f("uq_works_name")),
    )


def downgrade() -> None:
    op.drop_table("works")
    op.drop_table("work_types")
