"""fix pet work time table

Revision ID: e809792c446c
Revises: 48778bb90ea6
Create Date: 2024-08-27 22:17:49.227076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e809792c446c"
down_revision: Union[str, None] = "48778bb90ea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pet_work_times", sa.Column("id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "pet_work_times",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.alter_column(
        "pet_work_times",
        "work_time",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "pet_work_times",
        "next_work_time",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(),
        nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_pet_work_times_telegram_id"),
        "pet_work_times",
        ["telegram_id"],
    )
    op.create_foreign_key(
        op.f("fk_pet_work_times_work_id_works"),
        "pet_work_times",
        "works",
        ["work_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_pet_work_times_telegram_id_pets"),
        "pet_work_times",
        "pets",
        ["telegram_id"],
        ["telegram_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_pet_work_times_telegram_id_pets"),
        "pet_work_times",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_pet_work_times_work_id_works"),
        "pet_work_times",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_pet_work_times_telegram_id"), "pet_work_times", type_="unique"
    )
    op.alter_column(
        "pet_work_times",
        "next_work_time",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "pet_work_times",
        "work_time",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "pet_work_times",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("pet_work_times", "id")
    # ### end Alembic commands ###
